# Generated by Django 4.2.5 on 2023-09-18 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import telegrams.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('transmission_method', models.CharField(choices=[('Messagerie', 'Messagerie'), ('Fax', 'Fax'), ('Porte', 'Porte'), ('Autre', 'Autre')], max_length=100)),
                ('urgency_level', models.CharField(choices=[('Urgent', 'Urgent'), ('Semi-urgent', 'Semi-urgent'), ('Non urgent', 'Non urgent')], max_length=20)),
                ('telegram_type', models.CharField(choices=[('depart', 'Depart'), ('arrive', 'Arrive'), ('transit', 'Transit')], max_length=10)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_telegrams', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_telegrams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_telegram', models.FileField(blank=True, null=True, upload_to=telegrams.models.get_filename)),
                ('telegram_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='telegrams.telegram')),
            ],
        ),
    ]
