# Generated by Django 4.2.5 on 2023-09-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_alter_appuser_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='is_simple_user',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='details',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
